---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# hiv.prospect

This is a package to accompany the paper "Provider-initiated HIV testing and TB screening in the era of universal coverage: are the right people being reached? A cohort study in Blantyre, Malawi" by Luke Mair *et al*

## Installation

You can install the released version of hiv.prospect from [GitHub](https://github.com) with:

``` r
library(devtools)
install_github(petermacp/hiv.prospect)
```

## Analysis

Within the `data` folder, there are two datasets:
 - entry.rda, which contains anonymised individual-records of participants entering the clinic during the study period, and
 - exit.rda, which contains anonymised individual-records of participants interviewed whilst exiting the clinic during the study period.
 
With the `r` folder is the main analysis script `2018-01-08_analysis_hiv.prospect.Rmd`. Running this script will replicate the analysis in the manuscript.
